version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: echo "building"
      - run:
          command: echo "testing"
      - run:
          command: node -v
          
       - restore_cache:
          keys: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          command: npm install

      - save_cache:
          paths:
            - app/node_modules
          key: v1-dependencies-{{ "package.json" }}
