version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install   
      - run:
          name: Build 
          command: npm run build    
      - run:
          name: Deploy Over SSH
          command: |
            ssh "$SSH_USER@$SSH_HOST" "mkdir -p /var/www/html/occurrences"
