version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: echo "building"
      - run:
          command: echo "testing"
      - run:
          command: node -v
      - run:
          name: Install Dependencies
          command: npm install   
      - run:
          name: Build 
          command: npm run build
